targets = [ "//:date-time" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-numeric_conversion"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-algorithm"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-io"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-lexical_cast"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-tokenizer"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-serialization"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-winapi"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
version = "1.44.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
version = "1.44.0"
